title: Do something
name: zmunm
email: atheist2197@gmail.com
description: >-
  A blog for me who will forget everything
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zmunm.github.io"
github_username: zmunm
repository: zmunm/zmunm.github.io

author:
  name     : "Mingyu Kim"
  avatar   : "/assets/images/profile.jpg"
  bio      : "The man who reinvents the wheel"
  location : "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zmunm"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap

remote_theme: zmunm/minimal-mistakes
teaser: /assets/images/banner.jpg

permalink: /:categories/:title/

breadcrumbs: true #beta

include: ["_pages"]

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

search: true

paginate: 10 # amount of posts to show
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      author_profile: true
      share: true
      comments: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
